; Generated by AutoGUI 2.2.0a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Add, Edit, x42 y26 w403 h316 vText
Gui Add, Button, x213 y351 w85 h23 gsub1, Play

Gui Show, w481 h381, Virtual AHK player
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line

sub1:
{
   WinMinimize A
   WinMaximize Virtual Piano | The Original Best Piano App Online - Google Chrome
   WinActivate Virtual Piano | The Original Best Piano App Online - Google Chrome
   WinWaitActive Virtual Piano | The Original Best Piano App Online - Google Chrome
   sleep, 1000
   
   
   GuiControlGet, Text 
     flag=0
     time=800
   loop, parse, Text
   {
        if (A_LoopField = " ")
        {
            if (flag=0){
                sleep, (time/8)
            }
            sleep, (time/8)
        }
        else if (A_LoopField = "[")
        {
           
           flag=1

        }
         else if (A_LoopField = "]")
        {
           flag=0
           sleep, (time/4)
        }
         else if (A_LoopField = "|")
        {
           
             if (flag=0){
                sleep, (time/2)
            }
            sleep, (time/2)
        }
        else
        {
            send, %A_LoopField%
            if (flag=0){
                sleep, (time/4)
            }
            
        }
   }
   
}
Return